title: Information About Alyson
author: Alyson
email: amatecki2@ebnet.org
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Hello! This is my website with stuff about me on it. 
# social links
instagram_username: aly.datroller
github_username:  amatecki2

show_excerpts: true # set to false to remove excerpts on the homepage
